# Jekyll Project Setting
markdown    : kramdown
safe        : false
highlighter : pygments
comments    : true

# My Personal Information Setting
username    : JackDrogon
uname       : Drogon
baseurl     : 
name        : Drogon's Blog
title       : Drogon's Blog
