# Jekyll Project Setting
markdown    : redcarpet
safe        : false
highlighter : pygments
comments    : true

# My Personal Information Setting
username    : JackDrogon
uname       : Drogon
baseurl     : /blog
name        : Drogon's Blog
title       : Drogon's Blog
